# Generated by Django 3.2.7 on 2021-10-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caapp.service')),
            ],
        ),
    ]
