# Generated by Django 3.2.7 on 2021-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='overview',
            field=models.TextField(default='Taxation'),
        ),
    ]
